apiVersion: ecr.vesttoo.com/v1alpha1
kind: ecrpolicy-claim
metadata:
  name: ecr-repo-claim-pre-prod
  namespace: default
spec:
  parameters:
    ecrRegion: "us-east-1"
    ecrName: "crossplane-pre-prod"
  providerConfigName: aws-provider-config