apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: crossplane-saas-dev
patches:

## Subnet patches per environment
- target:
    kind: ekswithnode-claim
    name: marketplace-ekswithnode-claim
  path: ekswithnode-patch.yaml

nameSuffix: -dev