apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: crossplane-saas-demo
patches:

## Subnet patches per environment
- target:
    kind: rdswithmq-claim
    name: marketplace-rdswithmq-claim
  path: rdswithmq-patch.yaml

nameSuffix: -demo